<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="application.tests.TestApi-20171222150452" skipped="0" tests="4" time="2.181">
	<testcase classname="application.tests.TestApi" name="test_badOrderRequest" time="1.100"/>
	<testcase classname="application.tests.TestApi" name="test_badOrderRequest2" time="0.075"/>
	<testcase classname="application.tests.TestApi" name="test_orderRequest" time="0.926"/>
	<testcase classname="application.tests.TestApi" name="test_setApiKey" time="0.080">
		<failure message="404 != 200" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\stylesm\Desktop\test\OFS-MORE-Beta-Secured\source\payment_gateway\application\tests.py", line 71, in test_setApiKey
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
