<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="application.tests.TestApi-20180105172409" skipped="0" tests="5" time="1.354">
	<testcase classname="application.tests.TestApi" name="test_orderRequest" time="1.133"/>
	<testcase classname="application.tests.TestApi" name="test_serializerError" time="0.039"/>
	<testcase classname="application.tests.TestApi" name="test_setApiKey" time="0.005"/>
	<testcase classname="application.tests.TestApi" name="test_worldpayError" time="0.150"/>
	<testcase classname="application.tests.TestApi" name="test_getOrderInfo" time="0.027">
		<failure message="301 != 200" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\stylesm\Desktop\test\OFS-MORE-Beta-Secured\source\payment_gateway\application\tests.py", line 79, in test_getOrderInfo
    self.assertEqual(response.status_code, 200)
AssertionError: 301 != 200

Stdout:
b''
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[b''
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
