<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="2" name="application.tests.TestApi-20171222144613" skipped="0" tests="4" time="1.312">
	<testcase classname="application.tests.TestApi" name="test_badOrderRequest2" time="0.047"/>
	<testcase classname="application.tests.TestApi" name="test_badOrderRequest" time="0.234">
		<failure message="401 != 400" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\stylesm\Desktop\test\OFS-MORE-Beta-Secured\source\payment_gateway\application\tests.py", line 44, in test_badOrderRequest
    self.assertEqual(response.status_code, 400)
AssertionError: 401 != 400
]]>		</failure>
	</testcase>
	<testcase classname="application.tests.TestApi" name="test_orderRequest" time="0.187">
		<failure message="401 != 200" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\stylesm\Desktop\test\OFS-MORE-Beta-Secured\source\payment_gateway\application\tests.py", line 27, in test_orderRequest
    self.assertEqual(response.status_code, 200)
AssertionError: 401 != 200
]]>		</failure>
	</testcase>
	<testcase classname="application.tests.TestApi" name="test_badAPIOrderRequest" time="0.844">
		<error message="name 'settings' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\stylesm\Desktop\test\OFS-MORE-Beta-Secured\source\payment_gateway\application\tests.py", line 86, in test_badAPIOrderRequest
    "apiKey": settings.NOTIFY_API
NameError: name 'settings' is not defined
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
