<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="application.tests.TestApi-20180105172331" skipped="0" tests="5" time="1.796">
	<testcase classname="application.tests.TestApi" name="test_orderRequest" time="1.474"/>
	<testcase classname="application.tests.TestApi" name="test_serializerError" time="0.030"/>
	<testcase classname="application.tests.TestApi" name="test_setApiKey" time="0.003"/>
	<testcase classname="application.tests.TestApi" name="test_worldpayError" time="0.262"/>
	<testcase classname="application.tests.TestApi" name="test_getOrderInfo" time="0.027">
		<failure message="301 != 200" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\stylesm\Desktop\test\OFS-MORE-Beta-Secured\source\payment_gateway\application\tests.py", line 78, in test_getOrderInfo
    self.assertEqual(response.status_code, 200)
AssertionError: 301 != 200
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
